title: I Made Ocy Darma Putra
author: troke12
email: ochi@troke.id
description: > # this means to ignore newlines until "show_exerpts:"
  Hi, My name is I Made Ocy Darma Putra, just call me ocy or troke, currently i'm working on ITSEC Asia as System Administrator/DevOps R&D Team,
  <br/>feel free to contact me by email or linkedin profile!
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: troke12

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/darma_ochi
      icon: twitter-square
      color: blue
    - url: https://linkedin.com/in/troke
      icon: linkedin-square
      color: blue
    - url: https://github.com/troke12
      icon: github-square
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: troke12
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
